/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComposeEmailDialog: typeof import('./src/components/ComposeEmailDialog.vue')['default']
    ConflictResolution: typeof import('./src/components/ConflictResolution.vue')['default']
    ConnectedUsers: typeof import('./src/components/ConnectedUsers.vue')['default']
    CustomSearchBox: typeof import('./src/components/CustomSearchBox.vue')['default']
    GroupSelectorDialog: typeof import('./src/components/GroupSelectorDialog.vue')['default']
    IssueFilters: typeof import('./src/components/IssueFilters.vue')['default']
    IssuePagination: typeof import('./src/components/IssuePagination.vue')['default']
    IssueStats: typeof import('./src/components/IssueStats.vue')['default']
    IssueTable: typeof import('./src/components/IssueTable.vue')['default']
    RealTimeNotifications: typeof import('./src/components/RealTimeNotifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seachbox: typeof import('./src/components/Seachbox.vue')['default']
  }
}
